/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hamco
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPath_in = new javax.swing.JTextField();
        jButtonBuscaArquivo = new javax.swing.JButton();
        jLabelArquivoEntrada = new javax.swing.JLabel();
        jButtonUpmix = new javax.swing.JButton();
        jButtonPastaSaida = new javax.swing.JButton();
        jLabelPath_out = new javax.swing.JLabel();
        jLabelFileName = new javax.swing.JLabel();
        jLabelByName = new javax.swing.JLabel();
        jLabelEng = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Up-Mix de Áudio");
        getContentPane().setLayout(null);

        jTextFieldPath_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPath_inActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPath_in);
        jTextFieldPath_in.setBounds(10, 40, 500, 30);

        jButtonBuscaArquivo.setText("Buscar Arquivo");
        jButtonBuscaArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscaArquivo);
        jButtonBuscaArquivo.setBounds(520, 40, 130, 30);

        jLabelArquivoEntrada.setText("Up-Mix de áudio");
        getContentPane().add(jLabelArquivoEntrada);
        jLabelArquivoEntrada.setBounds(20, 10, 130, 20);

        jButtonUpmix.setText("UP MIX");
        jButtonUpmix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpmixActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpmix);
        jButtonUpmix.setBounds(93, 143, 160, 60);

        jButtonPastaSaida.setText("Pasta de Saída");
        jButtonPastaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPastaSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPastaSaida);
        jButtonPastaSaida.setBounds(520, 80, 130, 30);

        jLabelPath_out.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelPath_out);
        jLabelPath_out.setBounds(10, 80, 500, 30);
        getContentPane().add(jLabelFileName);
        jLabelFileName.setBounds(20, 280, 180, 0);

        jLabelByName.setText("by Hamilton");
        getContentPane().add(jLabelByName);
        jLabelByName.setBounds(880, 240, 70, 20);

        jLabelEng.setText("Engenharia");
        getContentPane().add(jLabelEng);
        jLabelEng.setBounds(880, 260, 70, 20);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\55929\\Documents\\NetBeansProjects\\ProjetoUpmix\\src\\main\\java\\imagens\\Java_logo_icon.png")); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 980, 300);

        setSize(new java.awt.Dimension(991, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPath_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPath_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPath_inActionPerformed

    private void jButtonBuscaArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaArquivoActionPerformed
        try{
            JFileChooser busca = new JFileChooser();
            busca.setCurrentDirectory(new File("C:\\PASTA_IN"));
            busca.setFileSelectionMode(JFileChooser.FILES_ONLY);
            busca.showOpenDialog(this);
            String arquivo = ""+busca.getSelectedFile().getPath();
            String file_name = ""+busca.getSelectedFile().getName();
            jTextFieldPath_in.setText(arquivo);
            jLabelFileName.setText(file_name);
        }
        catch(HeadlessException erro){
            
        }        
    }//GEN-LAST:event_jButtonBuscaArquivoActionPerformed

    private void jButtonUpmixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpmixActionPerformed
        if(jTextFieldPath_in.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Selecione um arquiva para converter !");
        }else if(jLabelPath_out.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma pasta para salvar o arquivo !");
        }else{
            Upmix up = new Upmix();
            String path_in = jTextFieldPath_in.getText();
            String path_out = jLabelPath_out.getText()+jLabelFileName.getText();
            up.Up(path_in, path_out);
        }
    }//GEN-LAST:event_jButtonUpmixActionPerformed

    private void jButtonPastaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPastaSaidaActionPerformed
        try{
            JFileChooser pasta = new JFileChooser();
            pasta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            pasta.setCurrentDirectory(new File("C:\\PASTA_OUT"));
            pasta.showOpenDialog(this);
            String pasta_saida = ""+pasta.getSelectedFile().getPath();
            jLabelPath_out.setText(pasta_saida+"\\");                       
        }
        catch(HeadlessException erro){
            
        }        
    }//GEN-LAST:event_jButtonPastaSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscaArquivo;
    private javax.swing.JButton jButtonPastaSaida;
    private javax.swing.JButton jButtonUpmix;
    private javax.swing.JLabel jLabelArquivoEntrada;
    private javax.swing.JLabel jLabelByName;
    private javax.swing.JLabel jLabelEng;
    private javax.swing.JLabel jLabelFileName;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPath_out;
    private javax.swing.JTextField jTextFieldPath_in;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\55929\\Documents\\NetBeansProjects\\ProjetoUpmix\\src\\main\\java\\imagens\\icon.png"));
    }
}
